name: 'bing_ads'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
  bing_ads:
    vars:
      ad_groups_table:      #schema.table
      campaigns_table:      #schema.table
      keywords_table:       #schema.table
      performance_table:    #schema.table
