name: 'bing_ads'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
  bing_ads:
    vars:
      etl:                                  #stitch or fivetran
      bing_accounts_table:                       #schema.table
      bing_ad_groups_table:                      #schema.table
      bing_ads_table:                            #schema.table
      bing_campaigns_table:                      #schema.table
      bing_keyword_performance_report_table:     #schema.table
